# Learning and Decision Making

## Laboratory 2: Markov decision problems

In the end of the lab, you should submit all code/answers written in the tasks marked as "Activity n. XXX", together with the corresponding outputs and any replies to specific questions posed to the e-mail <adi.tecnico@gmail.com>. Make sure that the subject is of the form [&lt;group n.&gt;] LAB &lt;lab n.&gt;.

### 1. Modeling

Consider once again the gridworld domain described in the Homework and which you modeled using a Markov decision process.

<img src="maze.png" width="200px">

Recall that:

* At each step, the agent may move in any of the four directions -- up, down, left and right. 
* Movement across a _grey_ cell division succeeds with a $0.8$ probability and fails with a $0.2$ probability. 
* Movements across colored cell divisions (blue or red) succeed with a $0.8$ probability _but only if the agent has the corresponding colored key_. Otherwise, they fail with probability $1$. 
* When the movement fails, the agent remains in the same cell. 
* To get a colored key, the agent simply needs to stand in the corresponding cell. 
* The goal of the agent is to reach the cell marked with **"G"**. 

**Throughout the lab, use $\gamma=0.99$.**

---

#### Activity 1.        

Implement your Markov decision process in Python. In particular,

* Create a list with all the states;
* Create a list with all the actions;
* For each action, define a `numpy` array with the corresponding transition probabilities;
* Define a `numpy`array with the costs. Make sure that:
    * The costs lie in the interval [0, 1]
    * The cost for standing in goal cell is minimal
    * The cost for standing in intermediate cells is maximal

The order for the states and actions used in the transition probability and cost matrices should match that in the lists of states and actions. 

**Note**: Don't forget to import `numpy`.

---

In [28]:
import numpy as np

#X = ["G", "R", "Rb", "B", "2", "2r", "2rb", "BR", "3", "3r", "3rb", "4", "4r", "4rb", "5", "5r", "5rb"]
#G-GoalCell, R-RedkeyCell, Rb-RedKeyCell with blue key, B-BlueCell, BR , BR - Blue with both keys


X = ["1br", "2", "2r", "2rb", "3", "3r", "3rb", "4", "4r", "4rb", "5", "5r", "5rb", "6rb", "7r", "7rb"]

A = ["up","down", "left", "right" ]

Pdown =  np.array(
           [[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0.2, 0, 0, 0, 0, 0, 0.8, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0.2, 0, 0, 0, 0, 0, 0.8, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0.2, 0, 0, 0, 0, 0, 0.8, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0.2, 0, 0, 0, 0, 0, 0.8, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0.2, 0, 0, 0, 0, 0, 0.8, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0.2, 0, 0, 0, 0, 0, 0.8, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0.2, 0, 0, 0, 0, 0, 0, 0.8, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0.2, 0, 0, 0, 0, 0, 0.8, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0, 0.2, 0, 0, 0, 0, 0, 0.8],
            [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
            [0.8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

Pup =  np.array(
           [[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0.8, 0, 0, 0, 0, 0, 0.2, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0.8, 0, 0, 0, 0, 0, 0.2, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0.8, 0, 0, 0, 0, 0, 0.2, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0.8, 0, 0, 0, 0, 0, 0.2, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0.8, 0, 0, 0, 0, 0, 0.2, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0.8, 0, 0, 0, 0, 0, 0.2, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0.8, 0, 0, 0, 0, 0, 0.2, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0, 0.8, 0, 0, 0, 0, 0, 0.2]])


Pleft =  np.array(
           [[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0.8, 0, 0.2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0.8, 0, 0, 0.2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0.8, 0, 0, 0.2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0.8, 0, 0, 0.2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0.8, 0, 0, 0.2, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0.8, 0, 0, 0.2, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0.8, 0, 0, 0.2, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0, 0.8, 0, 0, 0.2, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.8, 0.2, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])


Pright =  np.array([
            [0.2, 0, 0, 0.8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0.2, 0, 0, 0.8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0.2, 0, 0, 0.8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0.2, 0, 0, 0.8, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0.2, 0, 0, 0.8, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0.2, 0, 0, 0.8, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0, 0.2, 0, 0, 0.8, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.2, 0.8, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

P = 1/4*(Pright + Pleft+ Pup + Pdown)


C = np.array(
   [[1, 1, 1, 1],
    [1, 1, 1, 1],
    [1, 1, 1, 1],
    [1, 1, 1, 1],
    [1, 1, 1, 1],
    [1, 1, 1, 1],
    [1, 1, 1, 1],
    [1, 1, 1, 1],
    [1, 1, 1, 1],
    [1, 1, 1, 1],
    [1, 1, 1, 1],
    [1, 1, 1, 1],
    [1, 1, 1, 1],
    [0, 0, 0, 0],
    [1, 1, 1, 1],
    [1, 1, 1, 1]])

cu = C[:, 0, None]
cd = C[:, 1, None]
cl = C[:, 2, None]
cr = C[:, 3, None]

print(P)

[[0.8 0.  0.  0.2 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.6 0.  0.  0.2 0.  0.  0.2 0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.2 0.  0.4 0.  0.  0.2 0.  0.  0.2 0.  0.  0.  0.  0.  0.  0. ]
 [0.2 0.  0.  0.4 0.  0.  0.2 0.  0.  0.2 0.  0.  0.  0.  0.  0. ]
 [0.  0.2 0.  0.  0.6 0.  0.  0.  0.  0.  0.2 0.  0.  0.  0.  0. ]
 [0.  0.  0.2 0.  0.  0.6 0.  0.  0.  0.  0.  0.2 0.  0.  0.  0. ]
 [0.  0.  0.  0.2 0.  0.  0.6 0.  0.  0.  0.  0.  0.2 0.  0.  0. ]
 [0.  0.2 0.  0.  0.  0.  0.  0.4 0.  0.  0.2 0.  0.  0.  0.2 0. ]
 [0.  0.  0.2 0.  0.  0.  0.  0.  0.4 0.  0.  0.2 0.  0.  0.2 0. ]
 [0.  0.  0.  0.2 0.  0.  0.  0.  0.  0.4 0.  0.  0.2 0.  0.  0.2]
 [0.  0.  0.  0.  0.2 0.  0.  0.2 0.  0.  0.6 0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.2 0.  0.  0.2 0.  0.  0.6 0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.2 0.  0.  0.2 0.  0.  0.4 0.2 0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.2 0.8 0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.2 0.  0.  0.  0.  0.  0.8 

### 2. Prediction

You are now going to evaluate a given policy, computing the corresponding cost-to-go.

---

#### Activity 2.

Describe the policy that, in each state $x$, always moves the agent to the cell closest to the goal (irrespectively of the number of keys in the agent's possession). If multiple such cells exist, the agent should select randomly between the two.

For example, suppose that the agent is in cell 2. It should then select randomly between the actions $D$ and $R$. Conversely, suppose that the agent is in cell 4. The knight should then select actions $R$ with probability 1.

**Note:** The policy should be described as a vector with as many rows as there are states and as many columns as there are actions, where the entry $(x,a)$ has the probability of selecting action $a$ in state $x$.

---

In [29]:
# -- Insert your code here -- #
X = ["1br", "2", "2r", "2rb", "3", "3r", "3rb", "4", "4r", "4rb", "5", "5r", "5rb", "6rb", "7r", "7rb"]

A = ["up","down", "left", "right" ]


Policy = np.array([
    [0, 0, 0, 1],
    [0, 1, 0, 0],
    [0, 0, 1, 0],
    [0, 0.5, 0, 0.5],
    [0, 0, 1, 0],
    [0, 0, 1, 0],
    [0, 1, 0, 0],
    [0, 1, 0, 0],
    [1, 0, 0, 0],
    [0, 0, 0, 1],
    [0, 0, 1, 0],
    [0, 0, 1, 0],
    [0, 0, 0, 1],
    [1/3, 1/3, 0, 1/3],
    [1, 0, 0, 0],
    [1, 0, 0, 0]
])

print(Policy)

[[0.         0.         0.         1.        ]
 [0.         1.         0.         0.        ]
 [0.         0.         1.         0.        ]
 [0.         0.5        0.         0.5       ]
 [0.         0.         1.         0.        ]
 [0.         0.         1.         0.        ]
 [0.         1.         0.         0.        ]
 [0.         1.         0.         0.        ]
 [1.         0.         0.         0.        ]
 [0.         0.         0.         1.        ]
 [0.         0.         1.         0.        ]
 [0.         0.         1.         0.        ]
 [0.         0.         0.         1.        ]
 [0.33333333 0.33333333 0.         0.33333333]
 [1.         0.         0.         0.        ]
 [1.         0.         0.         0.        ]]


---

#### Activity 3.

Compute the cost-to-go function $J^\pi$ associated with the policy from Activity 2.

---

In [30]:
gama = 0.99

Ppi = Policy[:, 0, None]*Pup + Policy[:, 1, None]*Pdown + Policy[:, 2, None]*Pleft + Policy[:, 3, None]*Pright

Cpi = (Policy * C).sum(axis=1)

print("Ppi=\n%s" % Ppi)

print("\nCpi=%s" % Cpi)

I = np.identity(16)

Jpi = np.matmul(np.linalg.inv(I - gama * Ppi), Cpi)


print("\nJpi=%s" % Jpi)
print(Policy * C)

Ppi=
[[0.2 0.  0.  0.8 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.2 0.  0.  0.  0.  0.  0.8 0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.8 0.  0.2 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.2 0.  0.  0.4 0.  0.  0.4 0.  0.  0.  0.  0.  0. ]
 [0.  0.8 0.  0.  0.2 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.8 0.  0.  0.2 0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.2 0.  0.  0.  0.  0.  0.8 0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.2 0.  0.  0.  0.  0.  0.  0.8 0. ]
 [0.  0.  0.8 0.  0.  0.  0.  0.  0.2 0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.  0.2 0.  0.  0.8 0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.8 0.  0.  0.2 0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.8 0.  0.  0.2 0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.2 0.8 0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.8 0.  0.  0.  0.  0. 

### 3. Control

In this section you are going to compare value and policy iteration, both in terms of time and number of iterations.

---

#### Activity 4

Show that the policy in Activity 3 is _not_ optimal: use value iteration to compute $J^*$ and show that $J^*\neq J^\pi$. Track the time and the number of iterations taken to compute $J^*$.

**Note 1:** Stop the algorithm when the error between iterations is smaller than $10^{-8}$.

**Note 2:** You may find useful the function ``time()`` from the module ``time``.

---

In [46]:
import time

cu = C[:, 0, None]
cd = C[:, 1, None]
cl = C[:, 2, None]
cr = C[:, 3, None]


Jopt = np.zeros((16, 1))
err = 1
i = 0
gama = 0.99
start = time.time()

while err > 1e-8 :
    Qu = cu + gama * Pup.dot(Jopt)
    Qd = cd + gama * Pdown.dot(Jopt)
    Ql = cl + gama * Pleft.dot(Jopt)
    Qr = cr + gama * Pright.dot(Jopt)
    Jnew = np.min((Qu, Qd, Ql, Qr), axis=0)
    err = np.linalg.norm(Jnew - Jopt)
    i += 1
    Jopt = Jnew

end = time.time()
t = end - start

print("time elapsed = %s" % t)
print("iterations = %s\n" % i)
print("Jopt = ")
print(Jopt)

result = np.subtract(Jpi, Jopt.T)

print("Jpi - Jopt = %s" % result)

print("\nAs observed Jpi is not optimal, since Jopt is sometimes better than Jpi. This is concluded because some the costs of Jopt are smaller than Jpi.")


time elapsed = 0.004649162292480469
iterations = 31

Jopt = 
[[ 4.89502117]
 [10.67823015]
 [ 6.08086879]
 [ 3.69420073]
 [11.79196792]
 [ 7.25193028]
 [ 2.47821842]
 [ 9.55043002]
 [ 7.25193028]
 [ 2.47821842]
 [10.67823015]
 [ 8.40839   ]
 [ 1.24688279]
 [ 0.        ]
 [ 8.40839   ]
 [ 3.69420073]]
Jpi - Jopt = [[-1.77635684e-15  1.20053301e-10 -8.88178420e-16 -1.77635684e-15
   1.26529009e-09  3.28626015e-14 -8.88178420e-16  9.72377734e-12
   3.37507799e-14 -8.88178420e-16  1.20053301e-10  6.57252031e-13
   0.00000000e+00  1.43741913e-16  6.57252031e-13 -1.33226763e-15]]

As observed Jpi is not optimal, since Jopt is sometimes better than Jpi. This is concluded because some the costs of Jopt are smaller than Jpi.


---

#### Activity 5

Compute once again the optimal policy now using policy iteration. Track the time and number of iterations taken and compare to those of Activity 4.

**Note:** If you find that numerical errors affect your computations (especially when comparing two values/arrays) you may use the `numpy` function `isclose` with adequately set absolute and relative tolerance parameters (e.g., $10^{-8}$).

---

In [40]:
gama = 0.99
pi = Policy
err = 1
i = 0
I = np.eye(16)

start = time.time()

while err > 1e-8:
    Cpi = np.diag(pi[:, 0]).dot(cu) + np.diag(pi[:, 1]).dot(cd) + np.diag(pi[:, 2]).dot(cl) + np.diag(pi[:, 3]).dot(cr)
    Ppi = np.diag(pi[:, 0]).dot(Pup) + np.diag(pi[:, 1]).dot(Pdown) + np.diag(pi[:, 2]).dot(Pleft) + np.diag(pi[:, 3]).dot(Pright)
    J = np.linalg.inv(I - gama * Ppi).dot(Cpi)
    
    Qu = cu + gama * Pup.dot(J)
    Qd = cd + gama * Pdown.dot(J)
    Ql = cl + gama * Pleft.dot(J)
    Qr = cr + gama * Pright.dot(J)
    
    pinew = np.zeros((16, 4))
    pinew[:, 0, None] = np.isclose(Qu, np.min([Qu, Qd, Ql, Qr], axis = 0), atol=1e-8, rtol=1e-8).astype(int)
    pinew[:, 1, None] = np.isclose(Qd, np.min([Qu, Qd, Ql, Qr], axis = 0), atol=1e-8, rtol=1e-8).astype(int)
    pinew[:, 2, None] = np.isclose(Ql, np.min([Qu, Qd, Ql, Qr], axis = 0), atol=1e-8, rtol=1e-8).astype(int)
    pinew[:, 3, None] = np.isclose(Qr, np.min([Qu, Qd, Ql, Qr], axis = 0), atol=1e-8, rtol=1e-8).astype(int)
    
    pinew = pinew / np.sum(pinew, axis=1, keepdims=True)
    
    err = np.linalg.norm(pi - pinew)
    pi = pinew
    i += 1

end = time.time()
t = end - start

    
print("iterations: %s" % i)
print("time elapsed: %s\n" % t)
print("pi = \n%s" % pi)

iterations: 2
time elapsed: 0.0031960010528564453

pi = 
[[0.         0.         0.         1.        ]
 [0.         1.         0.         0.        ]
 [0.         0.         1.         0.        ]
 [0.         0.5        0.         0.5       ]
 [0.         0.5        0.5        0.        ]
 [0.         0.         1.         0.        ]
 [0.         1.         0.         0.        ]
 [0.         1.         0.         0.        ]
 [1.         0.         0.         0.        ]
 [0.         0.         0.         1.        ]
 [0.         0.         1.         0.        ]
 [0.5        0.         0.5        0.        ]
 [0.         0.         0.         1.        ]
 [0.33333333 0.33333333 0.         0.33333333]
 [1.         0.         0.         0.        ]
 [1.         0.         0.         0.        ]]


### 4. Simulation

Finally, in this section you will check whether the theoretical computations of the cost-to-go actually correspond to the cost incurred by an agent following a policy.

---

#### Activity 6

Suppose that the agent is where depicted in Fig. 1, and consider the situations (i) where it has no keys; (ii) where it has only the red key; (iii) where it has both keys. For each of the three situations,  

* Generate **100** trajectories of 10,000 steps each, following the optimal policy for the MDP. 
* For each trajectory, compute the accumulated (discounted) cost. 
* Compute the average cost over the 100 trajectories.
* Compare the resulting value with that computed in Activity 4. 

** Note:** The simulation may take a bit of time, don't despair ☺️.

---

In [45]:
OptPol = pi
print("Optimal Policy =")
print(OptPol)
#Probs = [Pup, Pdown, Pleft, Pright]
Probs = pi[:, 0, None]*Pup + pi[:, 1, None]*Pdown + pi[:, 2, None]*Pleft + pi[:, 3, None]*Pright
cost1 = np.zeros( (100, 1), dtype = np.float32 )
cost5 = np.zeros( (100, 1), dtype = np.float32 )
gama = 0.99

sum5_traj = 0
for i in range (0, 100):
    state = 11
    sum5 = 0
    for j in range(0, 10000):
        sum5 += (gama**j * C[state, 0])
        state = np.random.choice(16, p=Probs[state, :])
    sum5_traj += sum5


sum5r_traj = 0
for i in range (0, 100):
    state = 12
    sum5r = 0
    for j in range(0, 10000):
        sum5r += (gama**j * C[state, 0])
      
        state = np.random.choice(16, p=Probs[state, :])
    sum5r_traj += sum5r
    
sum5rb_traj = 0
for i in range (0, 100):
    state = 13
    sum5rb = 0
    for j in range(0, 10000):
        sum5rb += (gama**j * C[state, 0])
      
        state = np.random.choice(16, p=Probs[state, :])
    sum5rb_traj += sum5rb    

Optimal Policy =
[[0.         0.         0.         1.        ]
 [0.         1.         0.         0.        ]
 [0.         0.         1.         0.        ]
 [0.         0.5        0.         0.5       ]
 [0.         0.5        0.5        0.        ]
 [0.         0.         1.         0.        ]
 [0.         1.         0.         0.        ]
 [0.         1.         0.         0.        ]
 [1.         0.         0.         0.        ]
 [0.         0.         0.         1.        ]
 [0.         0.         1.         0.        ]
 [0.5        0.         0.5        0.        ]
 [0.         0.         0.         1.        ]
 [0.33333333 0.33333333 0.         0.33333333]
 [1.         0.         0.         0.        ]
 [1.         0.         0.         0.        ]]


In [47]:


print("Average Cost5 = %s" % (sum5_traj / 100))
print("Average Cost5r = %s" % (sum5r_traj / 100))
print("Average Cost5rb = %s" % (sum5rb_traj / 100))




Average Cost5 = 8.197885095710744
Average Cost5r = 1.3061089899999996
Average Cost5rb = 0.0


In [43]:
print(Probs)

[[0.2 0.  0.  0.8 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.2 0.  0.  0.  0.  0.  0.8 0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.8 0.  0.2 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.2 0.  0.  0.4 0.  0.  0.4 0.  0.  0.  0.  0.  0. ]
 [0.  0.4 0.  0.  0.2 0.  0.  0.  0.  0.  0.4 0.  0.  0.  0.  0. ]
 [0.  0.  0.8 0.  0.  0.2 0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.2 0.  0.  0.  0.  0.  0.8 0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.2 0.  0.  0.  0.  0.  0.  0.8 0. ]
 [0.  0.  0.8 0.  0.  0.  0.  0.  0.2 0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.  0.2 0.  0.  0.8 0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.8 0.  0.  0.2 0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.4 0.  0.  0.4 0.  0.  0.2 0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.2 0.8 0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.8 0.  0.  0.  0.  0.  0.2 